version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Root Django project
    schedule:
      interval: "weekly"
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/gateway_client" # Raspberry Pi Edge client
    schedule:
      interval: "weekly"
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
