# Generated by Django 6.0.2 on 2026-02-25 16:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "biometric_id",
                    models.CharField(
                        help_text="ID used in the biometric machine",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GatewayDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "mac_address",
                    models.CharField(
                        help_text="MAC Address of the Raspberry Pi",
                        max_length=17,
                        unique=True,
                    ),
                ),
                (
                    "api_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BiometricMachine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="Local IP address of the machine"
                    ),
                ),
                ("port", models.IntegerField(default=4370)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machines",
                        to="attendance_dashboard.gatewaydevice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "biometric_user_id",
                    models.CharField(
                        help_text="Raw user ID from the machine", max_length=50
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(help_text="Exact time of the punch"),
                ),
                (
                    "punch_type",
                    models.CharField(
                        default="Unknown",
                        help_text="Check-in, Check-out, etc.",
                        max_length=20,
                    ),
                ),
                (
                    "verification_mode",
                    models.IntegerField(
                        default=0, help_text="E.g., 0=Password, 1=Fingerprint, 15=Face"
                    ),
                ),
                ("is_synced", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="attendance_dashboard.biometricmachine",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_logs",
                        to="attendance_dashboard.employee",
                    ),
                ),
            ],
            options={
                "unique_together": {("biometric_user_id", "machine", "timestamp")},
            },
        ),
    ]
