# Generated by Django 6.0.2 on 2026-03-01 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="parent_phone",
            field=models.CharField(
                blank=True,
                help_text="For automated SMS alerts",
                max_length=15,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="StudentAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "success_score",
                    models.IntegerField(
                        default=100, help_text="0-100 Performance Score"
                    ),
                ),
                (
                    "punctuality_rate",
                    models.FloatField(
                        default=100.0, help_text="Percentage of on-time check-ins"
                    ),
                ),
                (
                    "attendance_consistency",
                    models.FloatField(
                        default=100.0, help_text="Frequency of attendance"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="attendance_dashboard.employee",
                    ),
                ),
            ],
        ),
    ]
