# Generated by Django 6.0.2 on 2026-03-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_dashboard", "0002_employee_parent_phone_studentanalytics"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="parent_email",
            field=models.EmailField(
                blank=True,
                help_text="For automated absence email alerts",
                max_length=254,
                null=True,
            ),
        ),
    ]
