# Generated by Django 6.0.2 on 2026-03-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_dashboard", "0003_employee_parent_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_time",
                    models.TimeField(
                        default="09:30",
                        help_text="Time to trigger the daily safety check",
                    ),
                ),
                (
                    "email_subject_template",
                    models.CharField(
                        default="Absence Alert: {first_name} {last_name}",
                        help_text="Available placeholders: {first_name}, {last_name}, {biometric_id}, {date}",
                        max_length=255,
                    ),
                ),
                (
                    "email_message_template",
                    models.TextField(
                        default="Dear Parent,\n\nThis is an automated alert. {first_name} {last_name} (ID: {biometric_id}) has not checked in as of {alert_time} today ({date}).\n\nPlease verify their safety.\n\nBest Regards,\nAttendance Team",
                        help_text="Available placeholders: {first_name}, {last_name}, {biometric_id}, {date}, {alert_time}",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable or disable automated alerts"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Alert Configuration",
                "verbose_name_plural": "Alert Configuration",
            },
        ),
    ]
