# Generated by Django 6.0.2 on 2026-03-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_dashboard", "0004_alertsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="faculty_email",
            field=models.EmailField(
                blank=True,
                help_text="For faculty absence alerts",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Student email", max_length=254, null=True
            ),
        ),
    ]
