# Generated by Django 6.0.2 on 2026-03-01 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_dashboard", "0006_notificationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="gatewaydevice",
            name="hardware_serial",
            field=models.CharField(
                blank=True,
                help_text="Unique hardware ID (e.g., CPU Serial)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="GatewaySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nonce", models.CharField(max_length=64, unique=True)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="attendance_dashboard.gatewaydevice",
                    ),
                ),
            ],
        ),
    ]
