# Generated by Django 6.0.2 on 2026-04-15 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_dashboard', '0007_gatewaydevice_hardware_serial_gatewaysession'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADD_USER', 'Add/Update User'), ('DELETE_USER', 'Delete User')], max_length=20)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_dashboard.employee')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue', to='attendance_dashboard.gatewaydevice')),
            ],
        ),
    ]
